In [ ]:
import pandas as pd
import numpy as np

pd.options.display.float_format = '{:,.2f}'.format


#Explode explode o df gerando mais linhas de acordo com as listas.
dic = {'A': [[1,2], 3, [4,5,6], []],
       'B': [1,2,3,4]}

df_dic = pd.DataFrame(dic)
df_dic = df_dic.explode('A')

df = pd.read_excel('dados-instagram.xlsx')

df.head()

,Tipo,Data,Curtidas,Comentários,Visualizações,Tags,Pessoas,Campanhas,Carrossel,Interacoes
0,Foto,2021-09-11,2858,16,NaN,Loja,N,N,NaN,2874
1,Foto,2021-09-11,2930,28,NaN,Loja/Produtos,N,N,NaN,2958
2,Foto,2021-09-11,2807,9,NaN,Loja,N,N,NaN,2816
3,Vídeo,2021-09-12,5115,49,"82,878.00",Produtos,N,N,NaN,5164
4,Foto,2021-09-13,4392,45,NaN,Produtos,S,N,NaN,4437

In [95]:
#Drop, 'derruba' uma coluna, passando a coluna e o axis 1 para coluna e axis 0 para linha
df = df.drop(['Visualizações'], axis=1)

In [96]:
display(df)
df.info()

,Tipo,Data,Curtidas,Comentários,Tags,Pessoas,Campanhas,Carrossel,Interacoes
0,Foto,2021-09-11,2858,16,Loja,N,N,NaN,2874
1,Foto,2021-09-11,2930,28,Loja/Produtos,N,N,NaN,2958
2,Foto,2021-09-11,2807,9,Loja,N,N,NaN,2816
3,Vídeo,2021-09-12,5115,49,Produtos,N,N,NaN,5164
4,Foto,2021-09-13,4392,45,Produtos,S,N,NaN,4437
5,Foto,2021-09-17,5359,62,Novos Produtos,N,S,S,5421
6,Foto,2021-09-19,21597,852,Novos Produtos,S,S,NaN,22449
7,Foto,2021-09-25,6346,33,Produtos,N,S,NaN,6379
8,Foto,2021-09-27,6355,89,Produtos,S,N,S,6444
9,Vídeo,2021-09-28,4056,81,Produtos,N,N,NaN,4137
10,Reels,2021-10-10,12894,249,Trends/Produtos,S,N,NaN,13143
11,Foto,2021-10-12,17831,391,NaN,S,S,NaN,18222
12,Foto,2021-10-21,6166,55,Novos Produtos,S,S,S,6221
13,Foto,2021-10-24,15940,612,Promoções,S,N,NaN,16552
14,Foto,2021-10-29,14121,184,Datas comemorativas,S,S,NaN,14305
15,Vídeo,2021-11-04,3646,71,Produtos,N,N,NaN,3717
16,Reels,2021-11-06,6376,137,Produtos,N,N,NaN,6513
17,Vídeo,2021-11-09,3213,60,Produtos,N,N,NaN,3273
18,Reels,2021-11-12,5493,59,Produtos,N,N,NaN,5552
19,Foto,2021-12-12,16086,268,NaN,S,S,NaN,16354
20,Foto,2021-12-16,2881,29,Produtos,N,N,NaN,2910
21,Foto,2021-12-23,8328,93,Produtos,S,N,S,8421
22,Foto,2021-12-26,18097,225,Influenciadores,S,S,NaN,18322
23,Foto,2021-12-28,8191,94,Influenciadores,S,N,NaN,8285
24,Vídeo,2021-12-30,17600,383,Trends,S,S,NaN,17983
25,Foto,2022-01-02,12193,138,Novos Produtos,S,N,S,12331
26,Foto,2022-01-08,24585,354,Datas comemorativas,S,S,S,24939
27,Foto,2022-01-11,16067,265,Novos Produtos,S,N,NaN,16332
28,Foto,2022-01-15,9936,119,Novos Produtos,S,N,S,10055
29,Foto,2022-01-19,8612,142,NaN,S,N,NaN,8754
30,Reels,2022-01-24,29981,502,Trends,S,S,NaN,30483
31,Foto,2022-01-27,10019,103,Novos Produtos,S,N,NaN,10122
32,IGTV,2022-02-04,9270,222,Dicas de como usar/Produtos,S,N,NaN,9492
33,Foto,2022-02-06,24655,186,Influenciadores,S,S,NaN,24841
34,Foto,2022-02-09,20660,292,Influenciadores,S,S,NaN,20952
35,IGTV,2022-02-10,8556,188,Dicas de como usar/Produtos,S,N,NaN,8744
36,Foto,2022-02-12,11802,102,Produtos,S,S,NaN,11904
37,Vídeo,2022-02-13,15219,357,Datas comemorativas,S,S,NaN,15576
38,Foto,2022-02-15,17687,213,NaN,S,N,NaN,17900
39,Foto,2022-02-17,37351,502,Promoções,S,S,NaN,37853
40,Foto,2022-02-21,21621,213,Influenciadores,S,S,S,21834
41,Foto,2022-02-22,12530,90,NaN,S,N,NaN,12620
42,Foto,2022-02-26,8544,72,Influenciadores,S,S,NaN,8616
43,Foto,2022-03-04,24399,266,NaN,S,S,NaN,24665
44,IGTV,2022-03-07,5918,116,Dicas de como usar/Novos Produtos,S,N,NaN,6034
45,Reels,2022-03-08,19621,275,Trends,S,S,NaN,19896
46,Foto,2022-03-09,4613,50,Influenciadores,S,N,NaN,4663
47,IGTV,2022-03-12,5489,77,Dicas de como usar/Novos Produtos,S,N,NaN,5566
48,Foto,2022-03-20,29084,479,Datas comemorativas/Promoções,S,S,NaN,29563
49,Foto,2022-03-22,9087,106,NaN,S,S,NaN,9193
50,Foto,2022-03-26,16551,186,NaN,S,N,NaN,16737
51,IGTV,2022-03-27,4934,65,Dicas de como usar/Produtos,S,N,NaN,4999

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Tipo         52 non-null     object
 1   Data         52 non-null     datetime64[ns]
 2   Curtidas     52 non-null     int64
 3   Comentários  52 non-null     int64
 4   Tags         44 non-null     object
 5   Pessoas      52 non-null     object
 6   Campanhas    52 non-null     object
 7   Carrossel    8 non-null      object
 8   Interacoes   52 non-null     int64
dtypes: datetime64[ns](1), int64(3), object(5)
memory usage: 3.8+ KB

In [97]:
df.Carrossel.value_counts()
df.loc[df.Carrossel.isnull(), 'Carrossel'] = 'N'
df['Carrossel']

0     N
1     N
2     N
3     N
4     N
5     S
6     N
7     N
8     S
9     N
10    N
11    N
12    S
13    N
14    N
15    N
16    N
17    N
18    N
19    N
20    N
21    S
22    N
23    N
24    N
25    S
26    S
27    N
28    S
29    N
30    N
31    N
32    N
33    N
34    N
35    N
36    N
37    N
38    N
39    N
40    S
41    N
42    N
43    N
44    N
45    N
46    N
47    N
48    N
49    N
50    N
51    N
Name: Carrossel, dtype: object

In [98]:
df.describe()
df.head()

,Tipo,Data,Curtidas,Comentários,Tags,Pessoas,Campanhas,Carrossel,Interacoes
0,Foto,2021-09-11,2858,16,Loja,N,N,N,2874
1,Foto,2021-09-11,2930,28,Loja/Produtos,N,N,N,2958
2,Foto,2021-09-11,2807,9,Loja,N,N,N,2816
3,Vídeo,2021-09-12,5115,49,Produtos,N,N,N,5164
4,Foto,2021-09-13,4392,45,Produtos,S,N,N,4437

In [91]:
#Groupby define um grupo e uma função para agregar as colunas e gerar indicadores.
df.groupby(["Tipo", "Pessoas"])[["Curtidas", "Comentários"]].mean()

               Curtidas  Comentários
Tipo  Pessoas
Foto  N        3,863.50        29.50
      S       15,236.67       226.20
IGTV  S        6,833.40       133.60
Reels N        5,934.50        98.00
      S       20,832.00       342.00
Vídeo N        4,007.50        65.25
      S       16,409.50       370.00

In [ ]:
#Juntando Filtro e groupby
df[df.Tipo == 'Foto'].groupby(["Carrossel"])[['Curtidas', 'Comentários']].mean()

In [99]:
df.groupby(["Tags"])[['Curtidas']].count()

                                   Curtidas
Tags
Datas comemorativas                       3
Datas comemorativas/Promoções             1
Dicas de como usar/Novos Produtos         2
Dicas de como usar/Produtos               3
Influenciadores                           7
Loja                                      2
Loja/Produtos                             1
Novos Produtos                            7
Produtos                                 12
Promoções                                 2
Trends                                    3
Trends/Produtos                           1

In [ ]:
df.Tags = df.Tags.str.split("//")

,Tipo,Data,Curtidas,Comentários,Tags,Pessoas,Campanhas,Carrossel,Interacoes
0,Foto,2021-09-11,2858,16,[Loja],N,N,N,2874
1,Foto,2021-09-11,2930,28,[Loja/Produtos],N,N,N,2958
2,Foto,2021-09-11,2807,9,[Loja],N,N,N,2816
3,Vídeo,2021-09-12,5115,49,[Produtos],N,N,N,5164
4,Foto,2021-09-13,4392,45,[Produtos],S,N,N,4437

In [112]:
df_dic

           A  B
0     [1, 2]  1
1          3  2
2  [4, 5, 6]  3
3         []  4

In [111]:
df = pd.read_excel('dados-instagram.xlsx')
df['Tags'] = df.Tags.str.split("//")
df.head()
# df = df.explode('Tags')

,Tipo,Data,Curtidas,Comentários,Visualizações,Tags,Pessoas,Campanhas,Carrossel,Interacoes
0,Foto,2021-09-11,2858,16,NaN,[Loja],N,N,NaN,2874
1,Foto,2021-09-11,2930,28,NaN,[Loja/Produtos],N,N,NaN,2958
2,Foto,2021-09-11,2807,9,NaN,[Loja],N,N,NaN,2816
3,Vídeo,2021-09-12,5115,49,"82,878.00",[Produtos],N,N,NaN,5164
4,Foto,2021-09-13,4392,45,NaN,[Produtos],S,N,NaN,4437